# Generated by Django 5.1.4 on 2025-01-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0002_userprofile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_provider',
            field=models.BooleanField(default=False),
        ),
    ]
