# Generated by Django 5.1.4 on 2025-01-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0004_userprofile_description_userprofile_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_provider',
        ),
    ]
