# Generated by Django 5.1.4 on 2025-01-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0007_userprofile_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
