# Generated by Django 5.1.4 on 2025-01-18 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0012_alter_userprofile_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='file',
            new_name='image',
        ),
    ]
