# Generated by Django 5.1.4 on 2025-01-18 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0013_rename_file_userprofile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='image',
            new_name='file',
        ),
    ]
