# Generated by Django 5.1.4 on 2025-01-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0019_alter_userprofile_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
