# Generated by Django 5.1.4 on 2025-01-19 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0021_userprofile_is_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_guest',
        ),
    ]
