# Generated by Django 5.1.4 on 2025-01-15 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0008_order_offer_detail_alter_order_business_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='coderr_app.offer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='offer_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='coderr_app.offerdetail'),
        ),
    ]
