# Generated by Django 5.1.4 on 2025-01-15 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0009_order_offer_alter_order_offer_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='offer',
        ),
    ]
