# Generated by Django 5.1.4 on 2025-01-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0010_remove_order_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='offer_detail',
        ),
        migrations.AlterField(
            model_name='order',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
